// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvs3htpfH2GXPzbTRTvu44VmIzd777VHY',
    appId: '1:32006943887:web:18431307af0f9820672cfa',
    messagingSenderId: '32006943887',
    projectId: 'reddit-clone-tutorial-dd734',
    authDomain: 'reddit-clone-tutorial-dd734.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-dd734.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDha-MJky0DgUzX0nFYwG7av-ciYgIRwKI',
    appId: '1:32006943887:android:675122a356b1a83f672cfa',
    messagingSenderId: '32006943887',
    projectId: 'reddit-clone-tutorial-dd734',
    storageBucket: 'reddit-clone-tutorial-dd734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7WMIwp-LxRY_JGHlhHcQhS2fo4xsMw2w',
    appId: '1:32006943887:ios:64557c72f2658ee1672cfa',
    messagingSenderId: '32006943887',
    projectId: 'reddit-clone-tutorial-dd734',
    storageBucket: 'reddit-clone-tutorial-dd734.appspot.com',
    iosClientId: '32006943887-2v6bkengi3t62j9e4m8fs1ufo5qcnhbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7WMIwp-LxRY_JGHlhHcQhS2fo4xsMw2w',
    appId: '1:32006943887:ios:01e54c8ccb13b084672cfa',
    messagingSenderId: '32006943887',
    projectId: 'reddit-clone-tutorial-dd734',
    storageBucket: 'reddit-clone-tutorial-dd734.appspot.com',
    iosClientId: '32006943887-gpji2e8g0bht5qc110s6hiiua85st7vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial.RunnerTests',
  );
}
